export const categories = ["All", "Website Design", "Ecommerce", "Mobile App", "SEO", "Branding", "Digital Marketing"];

export const projects = [
  {
    id: 1,
    slug: "brightpath-consulting-rebrand",
    title: "BrightPath Consulting Rebrand",
    category: "Website Design",
    client: "BrightPath Consulting",
    industry: "Professional Services",
    duration: "6 Weeks",
    tag: "Case Study",
    summary: "A full website redesign and brand refresh that tripled organic traffic and doubled lead conversions.",
    challenge: "BrightPath had an outdated website with high bounce rates (78%) and poor mobile performance. Their brand felt dated and was failing to communicate their premium positioning.",
    solution: "We designed a modern, responsive website with a completely new visual identity — refined typography, a cohesive color system, and conversion-optimized landing pages. We restructured the sitemap and implemented technical SEO from the ground up.",
    results: [
      { metric: "+312%", label: "Organic Traffic" },
      { metric: "-54%", label: "Bounce Rate" },
      { metric: "+89%", label: "Lead Conversions" },
      { metric: "1.2s", label: "Page Load Time" },
    ],
    color: "from-primary/20 to-primary/5",
    accentColor: "text-primary",
  },
  {
    id: 2,
    slug: "luxgoods-ecommerce-platform",
    title: "LuxGoods Ecommerce Platform",
    category: "Ecommerce",
    client: "LuxGoods Co.",
    industry: "Retail & Luxury Goods",
    duration: "10 Weeks",
    tag: "Case Study",
    summary: "A custom Shopify build with AI-powered recommendations that boosted revenue by 65% in year one.",
    challenge: "LuxGoods had a generic Shopify theme with poor product discovery, a clunky mobile checkout, and no personalization — resulting in a 1.2% conversion rate that was bleeding revenue.",
    solution: "We built a fully custom Shopify theme with curated product storytelling pages, a streamlined 3-step checkout, smart upsell logic, and integrations with Klaviyo for personalized email flows. Mobile was treated as the primary experience.",
    results: [
      { metric: "+65%", label: "Annual Revenue" },
      { metric: "3.8%", label: "Conversion Rate" },
      { metric: "-42%", label: "Cart Abandonment" },
      { metric: "+180%", label: "Mobile Revenue" },
    ],
    color: "from-accent/20 to-accent/5",
    accentColor: "text-accent",
  },
  {
    id: 3,
    slug: "fintrack-pro-mobile-app",
    title: "FinTrack Pro Mobile App",
    category: "Mobile App",
    client: "FinTrack Pro",
    industry: "Fintech",
    duration: "14 Weeks",
    tag: "Case Study",
    summary: "A cross-platform fintech app with 4.8-star ratings on both app stores, built from 0 to launch.",
    challenge: "FinTrack needed a mobile app that could handle real-time financial data, meet strict compliance requirements, and compete with established players — all within a 90-day timeline and limited budget.",
    solution: "We architected a React Native app with a secure Node.js backend, end-to-end encryption, Plaid integration for bank syncing, and a dashboard built around habit-forming data visualizations. Compliance documentation was handled in parallel with development.",
    results: [
      { metric: "4.8★", label: "App Store Rating" },
      { metric: "12K+", label: "Downloads in Month 1" },
      { metric: "90 Days", label: "0 to Launch" },
      { metric: "99.97%", label: "Uptime" },
    ],
    color: "from-primary/20 to-primary/5",
    accentColor: "text-primary",
  },
  {
    id: 4,
    slug: "healthfirst-seo-domination",
    title: "HealthFirst SEO Domination",
    category: "SEO",
    client: "HealthFirst Clinics",
    industry: "Healthcare",
    duration: "5 Months",
    tag: "Case Study",
    summary: "From page 4 to #1 on Google for high-intent keywords, generating 220+ new patient inquiries monthly.",
    challenge: "HealthFirst was invisible online despite being a top-rated clinic. With 12 locations, they had duplicate content issues, zero local SEO presence, and unoptimized service pages that Google couldn't rank.",
    solution: "We executed a full technical SEO audit, restructured the site architecture, built location-specific landing pages, and implemented a medical schema strategy. A white-hat link-building campaign targeting healthcare publications followed.",
    results: [
      { metric: "#1", label: "Google Ranking" },
      { metric: "+220%", label: "Organic Traffic" },
      { metric: "220+", label: "New Inquiries/Month" },
      { metric: "5 Months", label: "Time to Results" },
    ],
    color: "from-accent/20 to-accent/5",
    accentColor: "text-accent",
  },
  {
    id: 5,
    slug: "velo-brands-full-identity",
    title: "Velo Brands Full Identity",
    category: "Branding",
    client: "Velo Brands",
    industry: "Consumer Goods",
    duration: "4 Weeks",
    tag: "Case Study",
    summary: "A complete brand overhaul — logo, guidelines, packaging, and collateral — that repositioned Velo as a premium player.",
    challenge: "Velo's brand felt inconsistent and cheap. Their old logo was pixelated, their messaging was unclear, and their collateral was designed piecemeal by multiple vendors — none of it cohesive.",
    solution: "We started with brand positioning workshops, then developed a new logo suite, a comprehensive brand guidelines document, packaging redesigns across their top 12 SKUs, a full sales deck, and social media templates.",
    results: [
      { metric: "+38%", label: "Sales After Rebrand" },
      { metric: "12 SKUs", label: "Packaging Redesigned" },
      { metric: "4 Weeks", label: "Full Delivery" },
      { metric: "100%", label: "Team Adoption Rate" },
    ],
    color: "from-primary/20 to-primary/5",
    accentColor: "text-primary",
  },
  {
    id: 6,
    slug: "meridian-realty-ppc-turnaround",
    title: "Meridian Realty PPC Turnaround",
    category: "Digital Marketing",
    client: "Meridian Realty Group",
    industry: "Real Estate",
    duration: "60 Days",
    tag: "Case Study",
    summary: "Inherited underperforming ad accounts and delivered 4x ROAS within 60 days through restructured campaigns.",
    challenge: "Meridian was spending $18K/month on Google Ads with a 0.8x ROAS — effectively losing money on every click. Their campaigns had poor keyword targeting, irrelevant ad copy, and zero conversion tracking.",
    solution: "We rebuilt campaigns from scratch with tightly themed ad groups, location-specific ad copy, and conversion tracking for calls, forms, and map directions. Landing pages were A/B tested weekly and ad budgets dynamically allocated to top performers.",
    results: [
      { metric: "4x", label: "ROAS Achieved" },
      { metric: "-60%", label: "Cost Per Lead" },
      { metric: "+240%", label: "Qualified Leads" },
      { metric: "60 Days", label: "Time to Turnaround" },
    ],
    color: "from-accent/20 to-accent/5",
    accentColor: "text-accent",
  },
];